### PR TITLE
doc: added blog

### PR DESCRIPTION
**Pull request by maveraw**
Added Blog on IntelSGX in the main documentation for a better grasp of the subject.

### CODE REVIEW

**Comment by rjzak** [comment]
It is my opinion that all content on the Enarx website should be for Enarx and the supporting technologies. Any editorials should be part of Enarx, and not on third party domains. There shouldn't be a reason to look at a blog post about SGX for a project which uses SGX. The Enarx site should be a source of SGX information as needed by the project itself, or to links to Intel as the definitive and authoritative source. 

That said, having a link to Wasm.builders as part of a set of links related to community would be fine, but not for any one individual's blog.

**Comment by maveraw** [comment]
image
 Thanks.
So can we do this ??

**Comment by rjzak** [comment]
> image
> 
>  Thanks.
> 
> So can we do this ??
> 
> "Checkout relatable blogs on" ? 

How about a link to Wasm.builders under the community section of the menu? Just simply called something like "Wasm Builders" or "Wasm.builders", using the same icon as the others (box with arrow on the right) to indicate that the link takes the visitor to a new domain.

**Comment by maveraw** [comment]
I think we already have it in the initiative section.
image

**Comment by rjzak** [comment]
Perhaps @nickvidal can weigh in. Also, we should probably remove the cryptle hack challenge, that's been done for a while.

**Comment by maveraw** [comment]
@rjzak  My motive was to direct people to the topic-related blog. So that they don't have to search it on the WASM BUILDERS.  So the intel SGX used in ENARX, diving deep into its introduction could be helpful. That's why I wrote blogs specifically on a particular subject that we are using in order to build enarx. Linking just below what the topic actually is might save some time.

I Would like to know what you think bout this. Otherwise I understand with what your intents are here.https://github.com/enarx/website/pull/128#issuecomment-1464819556

**Comment by rjzak** [comment]
@maveraw Then it should be a link to a tag or category, not your blog post. But it's @nickvidal's decision. Or better, have some of the content as documentation in the Enarx website, where appropriate, not a separate site. All the information that people need to use Enarx should be on Enarx's page, or at some Intel/AMD source documentation. Blogs aren't authoritative.

**Pull request closed without merging**
