### PR TITLE
doc: publish practices to GitHub

### PR DESCRIPTION
**Pull request by dpal**
Signed-off-by: Dmitri Pal <dmitri@profian.com>

Publishing development practices stored in HackMD https://hackmd.io/team/enarx?nav=overview to Github.

### CODE REVIEW

**Comment by nickvidal** [comment]
Hi @dpal can you rework the PR please?

**Comment by dpal** [comment]
@nickvidal, I fixed the links. It just needs a review now.

**Review by nickvidal — APPROVED** [review]

**Comment by nickvidal** [comment]
Thank you @dpal , I hope all is well with you!

**Comment by nickvidal** [comment]
Would you like to expose these in the sidebar?

**Comment by dpal** [comment]
> Would you like to expose these in the sidebar?

No. These are internal documents of the project team.

**Pull request merged**
